/* **DO NOT EDIT THIS FILE** */
/*
 * Copyright 2004 Sun Microsystems, Inc. All Rights Reserved.
 *
 * This software is the proprietary information of Sun Microsystems, Inc.
 * Use is subject to license terms.
 *
 * This is a part of the Squawk JVM.
 */

package com.sun.squawk.vm;

import com.sun.squawk.compiler.*;
/**
 * This class defines the native method dispatch table.
 * It was automatically generated as a part of the build process
 * and should not be edited by hand.
 *
 * @author   Nik Shaylor
 * @author   Doug Simon
 */
abstract class InterpreterNative extends InterpreterSwitch {

    void do_nativeswitch() {
        nativebind(Native.com_sun_squawk_Address$add);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$add);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$addOffset);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$addOffset);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$and);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$and);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$diff);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$diff);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Address$eq);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$eq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$fromObject);
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_Address$fromObject);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$fromPrimitive);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_Address$fromPrimitive);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$hi);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$hi);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$hieq);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$hieq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$isMax);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$isMax);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$isZero);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$isZero);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$lo);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$lo);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$loeq);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$loeq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$max);
            invokenativeswapping(Native.com_sun_squawk_Address$max);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$ne);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$ne);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Address$or);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$or);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$roundDown);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$roundDown);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$roundDownToWord);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$roundDownToWord);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$roundUp);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$roundUp);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$roundUpToWord);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$roundUpToWord);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$sub);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$sub);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$subOffset);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$subOffset);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Address$toObject);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$toObject);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_Address$toUWord);
            nativepop(REF); // com.sun.squawk.Address (receiver)
            invokenativeswapping(Native.com_sun_squawk_Address$toUWord);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_Address$zero);
            invokenativeswapping(Native.com_sun_squawk_Address$zero);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$and);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$and);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$eq);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$eq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$fromPrimitive);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_UWord$fromPrimitive);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$hi);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$hi);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$hieq);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$hieq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$isMax);
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$isMax);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$isZero);
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$isZero);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$lo);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$lo);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$loeq);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$loeq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$max);
            invokenativeswapping(Native.com_sun_squawk_UWord$max);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$ne);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$ne);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$or);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$or);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$toInt);
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$toInt);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$toOffset);
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$toOffset);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$toPrimitive);
            nativepop(OOP); // com.sun.squawk.UWord (receiver)
            invokenativeswapping(Native.com_sun_squawk_UWord$toPrimitive);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_UWord$zero);
            invokenativeswapping(Native.com_sun_squawk_UWord$zero);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$add);
            nativepop(INT); // int
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$add);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$bytesToWords);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$bytesToWords);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$eq);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$eq);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$fromPrimitive);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_Offset$fromPrimitive);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$ge);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$ge);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$gt);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$gt);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$isZero);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$isZero);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$le);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$le);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$lt);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$lt);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$ne);
            nativepop(WORD); // com.sun.squawk.Offset
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$ne);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$sub);
            nativepop(INT); // int
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$sub);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$toInt);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$toInt);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$toPrimitive);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$toPrimitive);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$toUWord);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$toUWord);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$wordsToBytes);
            nativepop(WORD); // com.sun.squawk.Offset (receiver)
            invokenativeswapping(Native.com_sun_squawk_Offset$wordsToBytes);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_Offset$zero);
            invokenativeswapping(Native.com_sun_squawk_Offset$zero);
            nativepush(WORD); // com.sun.squawk.Offset
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$charAt);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.String
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$charAt);
            nativepush(INT); // char
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$copyTypes);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$copyTypes);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getAddress);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getAddress);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getAsByte);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getAsByte);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getAsInt);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getAsInt);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getAsShort);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getAsShort);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getAsUWord);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getAsUWord);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getByte);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getByte);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getChar);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getChar);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getInt);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getInt);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getLong);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getLong);
            nativepush(LONG); // long
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getLongAtWord);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getLongAtWord);
            nativepush(LONG); // long
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getObject);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getObject);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getShort);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getShort);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getType);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getType);
            nativepush(INT); // byte
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$getUWord);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$getUWord);
            nativepush(OOP); // com.sun.squawk.UWord
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setAddress);
            nativepop(OOP); // java.lang.Object
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setAddress);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setArrayTypes);
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // byte
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setArrayTypes);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setByte);
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setByte);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setChar);
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setChar);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setInt);
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setInt);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setLong);
            nativepop(LONG); // long
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setLong);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setLongAtWord);
            nativepop(LONG); // long
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setLongAtWord);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setObject);
            nativepop(OOP); // java.lang.Object
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setObject);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setShort);
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setShort);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setType);
            nativepop(INT); // int
            nativepop(INT); // byte
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setType);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$setUWord);
            nativepop(OOP); // com.sun.squawk.UWord
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$setUWord);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$swap);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$swap);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$swap2);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$swap2);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$swap4);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$swap4);
            nativedone();

        nativebind(Native.com_sun_squawk_NativeUnsafe$swap8);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_NativeUnsafe$swap8);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$addToClassStateCache);
            nativepop(OOP); // java.lang.Object
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$addToClassStateCache);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$addressResult);
            invokenativeswapping(Native.com_sun_squawk_VM$addressResult);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$allocate);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$allocate);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_VM$allocateVirtualStack);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$allocateVirtualStack);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$asKlass);
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$asKlass);
            nativepush(OOP); // com.sun.squawk.Klass
            nativedone();

        nativebind(Native.com_sun_squawk_VM$callStaticNoParm);
            nativepop(INT); // int
            nativepop(OOP); // com.sun.squawk.Klass
            invokenativeswapping(Native.com_sun_squawk_VM$callStaticNoParm);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$callStaticOneParm);
            nativepop(OOP); // java.lang.Object
            nativepop(INT); // int
            nativepop(OOP); // com.sun.squawk.Klass
            invokenativeswapping(Native.com_sun_squawk_VM$callStaticOneParm);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$deadbeef);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$deadbeef);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$doubleToLongBits);
            nativepop(DOUBLE); // double
            invokenativeswapping(Native.com_sun_squawk_VM$doubleToLongBits);
            nativepush(LONG); // long
            nativedone();

        nativebind(Native.com_sun_squawk_VM$executeCIO);
            nativepop(OOP); // java.lang.Object
            nativepop(OOP); // java.lang.Object
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$executeCIO);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$executeCOG);
            nativepop(OOP); // com.sun.squawk.ObjectMemorySerializer$ControlBlock
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$executeCOG);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$executeGC);
            nativepop(INT); // boolean
            invokenativeswapping(Native.com_sun_squawk_VM$executeGC);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$fatalVMError);
            invokenativeswapping(Native.com_sun_squawk_VM$fatalVMError);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$finalize);
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$finalize);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$floatToIntBits);
            nativepop(FLOAT); // float
            invokenativeswapping(Native.com_sun_squawk_VM$floatToIntBits);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getBranchCount);
            invokenativeswapping(Native.com_sun_squawk_VM$getBranchCount);
            nativepush(LONG); // long
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getFP);
            invokenativeswapping(Native.com_sun_squawk_VM$getFP);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalAddr);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalAddr);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalAddrCount);
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalAddrCount);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalInt);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalInt);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalIntCount);
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalIntCount);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalOop);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalOop);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalOopCount);
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalOopCount);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getGlobalOopTable);
            invokenativeswapping(Native.com_sun_squawk_VM$getGlobalOopTable);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getInterruptStatus);
            nativepop(INT); // int
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$getInterruptStatus);
            nativepush(LONG); // long
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getMP);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$getMP);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getPreviousFP);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$getPreviousFP);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$getPreviousIP);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$getPreviousIP);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_VM$hasVirtualMonitorObject);
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$hasVirtualMonitorObject);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_VM$hashcode);
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$hashcode);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$intBitsToFloat);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$intBitsToFloat);
            nativepush(FLOAT); // float
            nativedone();

        nativebind(Native.com_sun_squawk_VM$invalidateClassStateCache);
            invokenativeswapping(Native.com_sun_squawk_VM$invalidateClassStateCache);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_VM$isBigEndian);
            invokenativeswapping(Native.com_sun_squawk_VM$isBigEndian);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_VM$isInKernel);
            invokenativeswapping(Native.com_sun_squawk_VM$isInKernel);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_VM$longBitsToDouble);
            nativepop(LONG); // long
            invokenativeswapping(Native.com_sun_squawk_VM$longBitsToDouble);
            nativepush(DOUBLE); // double
            nativedone();

        nativebind(Native.com_sun_squawk_VM$math);
            nativepop(DOUBLE); // double
            nativepop(DOUBLE); // double
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$math);
            nativepush(DOUBLE); // double
            nativedone();

        nativebind(Native.com_sun_squawk_VM$pause);
            invokenativeswapping(Native.com_sun_squawk_VM$pause);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$removeVirtualMonitorObject);
            invokenativeswapping(Native.com_sun_squawk_VM$removeVirtualMonitorObject);
            nativepush(OOP); // java.lang.Object
            nativedone();

        nativebind(Native.com_sun_squawk_VM$sendInterrupt);
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$sendInterrupt);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$serviceResult);
            invokenativeswapping(Native.com_sun_squawk_VM$serviceResult);
            nativepush(INT); // int
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setGlobalAddr);
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$setGlobalAddr);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setGlobalInt);
            nativepop(INT); // int
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$setGlobalInt);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setGlobalOop);
            nativepop(INT); // int
            nativepop(OOP); // java.lang.Object
            invokenativeswapping(Native.com_sun_squawk_VM$setGlobalOop);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setPreviousFP);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$setPreviousFP);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setPreviousIP);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$setPreviousIP);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setupAlarmInterval);
            nativepop(INT); // int
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$setupAlarmInterval);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$setupInterrupt);
            nativepop(OOP); // java.lang.String
            nativepop(INT); // int
            invokenativeswapping(Native.com_sun_squawk_VM$setupInterrupt);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$threadSwitch);
            invokenativeswapping(Native.com_sun_squawk_VM$threadSwitch);
            nativedone();

        nativebind(Native.com_sun_squawk_VM$zeroWords);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_VM$zeroWords);
            nativedone();

        nativebind(Native.com_sun_squawk_CheneyCollector$memoryProtect);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_CheneyCollector$memoryProtect);
            nativedone();

        nativebind(Native.com_sun_squawk_ServiceOperation$cioExecute);
            invokenativeswapping(Native.com_sun_squawk_ServiceOperation$cioExecute);
            nativedone();

        nativebind(Native.com_sun_squawk_GarbageCollector$collectGarbageInC);
            nativepop(INT); // boolean
            nativepop(REF); // com.sun.squawk.Address
            nativepop(OOP); // com.sun.squawk.GarbageCollector (receiver)
            invokenativeswapping(Native.com_sun_squawk_GarbageCollector$collectGarbageInC);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_GarbageCollector$copyObjectGraphInC);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(OOP); // com.sun.squawk.ObjectMemorySerializer$ControlBlock
            nativepop(REF); // com.sun.squawk.Address
            nativepop(OOP); // com.sun.squawk.GarbageCollector (receiver)
            invokenativeswapping(Native.com_sun_squawk_GarbageCollector$copyObjectGraphInC);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_GarbageCollector$hasNativeImplementation);
            nativepop(OOP); // com.sun.squawk.GarbageCollector (receiver)
            invokenativeswapping(Native.com_sun_squawk_GarbageCollector$hasNativeImplementation);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$clearBitFor);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$clearBitFor);
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$clearBitsFor);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$clearBitsFor);
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$getAddressForBitmapWord);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$getAddressForBitmapWord);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$getAddressOfBitmapWordFor);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$getAddressOfBitmapWordFor);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$initialize);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(INT); // int
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$initialize);
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$iterate);
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$iterate);
            nativepush(REF); // com.sun.squawk.Address
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$setBitFor);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$setBitFor);
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$setBitsFor);
            nativepop(REF); // com.sun.squawk.Address
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$setBitsFor);
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$testAndSetBitFor);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$testAndSetBitFor);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_Lisp2Bitmap$testBitFor);
            nativepop(REF); // com.sun.squawk.Address
            invokenativeswapping(Native.com_sun_squawk_Lisp2Bitmap$testBitFor);
            nativepush(INT); // boolean
            nativedone();

        nativebind(Native.com_sun_squawk_VM$lcmp);
            nativepop(LONG); // long
            nativepop(LONG); // long
            invokenativeswapping(Native.com_sun_squawk_VM$lcmp);
            nativepush(INT); // int
            nativedone();

    }
    abstract protected void nativepop(Type t);
    abstract protected void nativepush(Type t);
    abstract protected void nativebind(int x);
    abstract protected void nativedone();
}
